### ISSUE TITLE
Issue with SpongeForge in 1.10.2 Minecraft.

### ISSUE THREAD

**Issue by KaneHart** [MinecraftMarket/MinecraftMarket-Plugin#19]
For some reason if I do say a command like say blah and require the user online it will not work. But when they go offline it works.

![fdsfsd](https://user-images.githubusercontent.com/425853/33412260-4488711e-d558-11e7-8e8c-a383c353855d.png)

forge-1.10.2-12.18.3.2477-universal.jar
spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar
LuckPerms-Sponge-4.0.16.jar
MinecraftMarket-3.6.3.jar
I tried a very old version too MinecraftMarket-3.5.2.jar 

![evpamh2](https://user-images.githubusercontent.com/425853/33412279-64268f88-d558-11e7-9999-d4d1c7b0ffe3.png)

**Comment by KaneHart** [comment]
I tried with a super slim version of things and yeah for sure broken:

![hiq4bku](https://user-images.githubusercontent.com/425853/33412518-cab2921e-d559-11e7-8d0b-59949839e4e6.png)

**Comment by R4G3-BABY** [comment]
Fixed on commit 6320a08. Sorry!
